export const treks = [
  {
    id: 1,
    slug: "hampta-pass",
    name: "Hampta Pass",
    location: "Himachal Pradesh",
    region: "India",
    image:
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1200&q=85",
    ],
    tagline: "A dramatic crossing from green valleys into the high desert.",
    description:
      "Hampta Pass is the Himalayas in one unforgettable frame: lush meadows, glacial rivers, a moon-like pass, and a warm night at Chandratal Lake.",
    duration: "5D / 4N",
    difficulty: "Moderate",
    altitude: "14,100 Ft",
    distance: "35 km",
    baseCamp: "Manali",
    rating: 4.9,
    reviewCount: 184,
    price: 12900,
    originalPrice: 15900,
    badge: "Fast filling",
    categories: ["Himalayas", "High Pass", "Camping"],
    batches: [
      { id: 101, startDate: "Jun 14", endDate: "Jun 18, 2026", slotsLeft: 6, price: 12900 },
      { id: 102, startDate: "Jun 28", endDate: "Jul 02, 2026", slotsLeft: 12, price: 12900 },
      { id: 103, startDate: "Jul 12", endDate: "Jul 16, 2026", slotsLeft: 3, price: 13900 },
    ],
    itinerary: [
      { day: 1, title: "Arrival in Manali", description: "Meet your crew, gear check, and a slow evening by the Beas.", distance: "—", altitude: "6,700 Ft", meal: "Dinner" },
      { day: 2, title: "Manali to Jobra · Chika", description: "A short forest trail opens into wide alpine meadows.", distance: "8 km", altitude: "10,100 Ft", meal: "Breakfast, lunch, dinner" },
      { day: 3, title: "Chika to Balu Ka Ghera", description: "Cross glacial streams under the watch of Indrasen peak.", distance: "9 km", altitude: "12,900 Ft", meal: "Breakfast, lunch, dinner" },
      { day: 4, title: "Cross Hampta Pass · Shea Goru", description: "The big day: snowfields, a 14,100 Ft pass, and Spiti's stark landscape.", distance: "14 km", altitude: "14,100 Ft", meal: "Breakfast, lunch, dinner" },
    ],
  },
  {
    id: 2,
    slug: "nag-tibba",
    name: "Nag Tibba",
    location: "Uttarakhand",
    region: "India",
    image:
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=1200&q=85",
    ],
    tagline: "A first Himalayan summit, just a night bus away.",
    description:
      "The perfect reset for a long weekend. Walk through cedar forests, sleep under an ocean of stars, and catch the sunrise over five Himalayan ranges.",
    duration: "2D / 1N",
    difficulty: "Easy",
    altitude: "9,910 Ft",
    distance: "16 km",
    baseCamp: "Pantwari",
    rating: 4.8,
    reviewCount: 327,
    price: 3490,
    originalPrice: 4490,
    badge: "Friday night bus",
    categories: ["Weekend", "Beginner", "Himalayas"],
    batches: [
      { id: 201, startDate: "Jun 06", endDate: "Jun 07, 2026", slotsLeft: 8, price: 3490 },
      { id: 202, startDate: "Jun 13", endDate: "Jun 14, 2026", slotsLeft: 16, price: 3490 },
      { id: 203, startDate: "Jun 20", endDate: "Jun 21, 2026", slotsLeft: 4, price: 3990 },
    ],
    itinerary: [
      { day: 1, title: "Dehradun to Pantwari · Camp", description: "A scenic drive to the trailhead, followed by a forest climb into camp.", distance: "5 km", altitude: "8,500 Ft", meal: "Lunch, dinner" },
      { day: 2, title: "Summit sunrise · Return", description: "Climb to the summit for sunrise, then descend for a late breakfast.", distance: "11 km", altitude: "9,910 Ft", meal: "Breakfast, lunch" },
    ],
  },
  {
    id: 3,
    slug: "valley-of-flowers",
    name: "Valley of Flowers",
    location: "Uttarakhand",
    region: "India",
    image:
      "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1200&q=85",
    ],
    tagline: "A living carpet of alpine blooms beneath Nanda Devi.",
    description:
      "Every monsoon, the Valley of Flowers turns into a surreal high-altitude garden. Pair it with Hemkund Sahib for a week of rare mountain stillness.",
    duration: "6D / 5N",
    difficulty: "Moderate",
    altitude: "14,107 Ft",
    distance: "38 km",
    baseCamp: "Govindghat",
    rating: 4.9,
    reviewCount: 216,
    price: 14900,
    originalPrice: 17900,
    badge: "Monsoon special",
    categories: ["Monsoon", "Wildflowers", "Slow travel"],
    batches: [
      { id: 301, startDate: "Jul 04", endDate: "Jul 09, 2026", slotsLeft: 10, price: 14900 },
      { id: 302, startDate: "Jul 18", endDate: "Jul 23, 2026", slotsLeft: 7, price: 14900 },
    ],
    itinerary: [
      { day: 1, title: "Arrival in Govindghat", description: "Settle into the valley, meet the team, and prepare for tomorrow.", distance: "—", altitude: "6,200 Ft", meal: "Dinner" },
      { day: 2, title: "Govindghat to Ghangaria", description: "Follow the Pushpawati river through a cool forest to base camp.", distance: "14 km", altitude: "10,000 Ft", meal: "Breakfast, lunch, dinner" },
      { day: 3, title: "Into the Valley of Flowers", description: "A full day among rare blooms, waterfalls, and wide-open mountain light.", distance: "8 km", altitude: "12,700 Ft", meal: "Breakfast, lunch, dinner" },
    ],
  },
  {
    id: 4,
    slug: "triund",
    name: "Triund",
    location: "Himachal Pradesh",
    region: "India",
    image:
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85",
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85",
    ],
    tagline: "Big views, little effort, zero reason to stay in.",
    description:
      "Triund's easy trail is a gateway to the Dhauladhar: a quick climb through pine forests to one of the most rewarding camps in the north.",
    duration: "2D / 1N",
    difficulty: "Easy",
    altitude: "9,760 Ft",
    distance: "14 km",
    baseCamp: "McLeod Ganj",
    rating: 4.7,
    reviewCount: 403,
    price: 2990,
    originalPrice: 3990,
    badge: "Easy escape",
    categories: ["Weekend", "Beginner", "Camping"],
    batches: [
      { id: 401, startDate: "Jun 06", endDate: "Jun 07, 2026", slotsLeft: 18, price: 2990 },
      { id: 402, startDate: "Jun 27", endDate: "Jun 28, 2026", slotsLeft: 11, price: 2990 },
    ],
    itinerary: [
      { day: 1, title: "McLeod Ganj to Triund", description: "Climb through oak and rhododendron forests to camp above the clouds.", distance: "7 km", altitude: "9,760 Ft", meal: "Lunch, dinner" },
      { day: 2, title: "Sunrise · Descend", description: "Coffee with a view, then an easy descent back into town.", distance: "7 km", altitude: "5,800 Ft", meal: "Breakfast" },
    ],
  },
];

export const trailReports = [
  { id: 1, trail: "Hampta Pass", region: "Himachal Pradesh", status: "open", temperature: "8°C", weather: "Clear skies", updatedAt: "12 min ago", note: "Pass window is looking excellent this week." },
  { id: 2, trail: "Valley of Flowers", region: "Uttarakhand", status: "caution", temperature: "14°C", weather: "Light showers", updatedAt: "28 min ago", note: "Carry a rain cover. Trail is clear above Ghangaria." },
  { id: 3, trail: "Roopkund", region: "Uttarakhand", status: "closed", temperature: "-2°C", weather: "Heavy snow", updatedAt: "1 hr ago", note: "Route is closed for seasonal restoration." },
  { id: 4, trail: "Triund", region: "Himachal Pradesh", status: "open", temperature: "17°C", weather: "Sunny", updatedAt: "42 min ago", note: "Clear visibility from camp to the Dhauladhar." },
];