export const treks = [
  {
    id: 1,
    slug: "kedarkantha",
    name: "Kedarkantha Summit Trek",
    location: "Uttarakhand",
    region: "India",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85",
    ],
    tagline: "Dense pine forests, snow glades, and dramatic summit ridge.",
    description: "Kedarkantha is famous for its dramatic 360-degree summit views of Swargarohini, Bandarpoonch, and Black Peak.",
    duration: "6D / 5N",
    difficulty: "Moderate",
    altitude: "12,500 Ft",
    distance: "23 km",
    baseCamp: "Sankri",
    rating: 4.9,
    reviewCount: 280,
    price: 8999,
    originalPrice: 10999,
    badge: "Bestseller",
    categories: ["Himalayas", "Summit", "Snow"],
    batches: [
      { id: 101, startDate: "Jun 14", endDate: "Jun 18, 2026", slotsLeft: 6, price: 8999 },
      { id: 102, startDate: "Jun 28", endDate: "Jul 02, 2026", slotsLeft: 12, price: 8999 },
      { id: 103, startDate: "Jul 12", endDate: "Jul 16, 2026", slotsLeft: 4, price: 9499 },
    ],
    itinerary: [
      { day: 1, title: "Drive to Sankri (6,400 ft)", description: "Scenic drive along Yamuna and Tons rivers.", distance: "—", altitude: "6,400 Ft", meal: "Dinner" },
      { day: 2, title: "Sankri to Juda Ka Talab", description: "Climb through pine and maple forests to a frozen lake camp.", distance: "5 km", altitude: "9,100 Ft", meal: "Breakfast, lunch, dinner" },
      { day: 3, title: "Juda Ka Talab to Base Camp", description: "Short climb into wide snow glades surrounded by Himalayan peaks.", distance: "4 km", altitude: "11,250 Ft", meal: "Breakfast, lunch, dinner" },
      { day: 4, title: "Summit Push & Descend to Hargaon", description: "Early 4:00 AM climb to the summit ridge for sunrise.", distance: "7 km", altitude: "12,500 Ft", meal: "Breakfast, lunch, dinner" },
    ],
  },
  {
    id: 2,
    slug: "hampta-pass",
    name: "Hampta Pass Crossover",
    location: "Himachal Pradesh",
    region: "India",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85",
    ],
    tagline: "A dramatic crossing from green valleys into the high desert.",
    description: "Hampta Pass is the Himalayas in one unforgettable frame: lush meadows, glacial rivers, a moon-like pass, and a warm night at Chandratal Lake.",
    duration: "5D / 4N",
    difficulty: "Moderate",
    altitude: "14,100 Ft",
    distance: "35 km",
    baseCamp: "Manali",
    rating: 4.9,
    reviewCount: 184,
    price: 11199,
    originalPrice: 13999,
    badge: "Fast filling",
    categories: ["Himalayas", "High Pass", "Camping", "Monsoon"],
    batches: [
      { id: 201, startDate: "Jun 14", endDate: "Jun 18, 2026", slotsLeft: 6, price: 11199 },
      { id: 202, startDate: "Jun 28", endDate: "Jul 02, 2026", slotsLeft: 12, price: 11199 },
      { id: 203, startDate: "Jul 12", endDate: "Jul 16, 2026", slotsLeft: 3, price: 11999 },
    ],
    itinerary: [
      { day: 1, title: "Manali to Jobra & Chika", description: "Short forest trail opening into wide alpine meadows.", distance: "8 km", altitude: "10,100 Ft", meal: "Breakfast, lunch, dinner" },
      { day: 2, title: "Chika to Balu Ka Ghera", description: "Cross glacial streams under the watch of Indrasen peak.", distance: "9 km", altitude: "12,900 Ft", meal: "Breakfast, lunch, dinner" },
      { day: 3, title: "Cross Hampta Pass to Shea Goru", description: "The big day: snowfields, a 14,100 Ft pass, and Spiti's stark landscape.", distance: "14 km", altitude: "14,100 Ft", meal: "Breakfast, lunch, dinner" },
    ],
  },
  {
    id: 3,
    slug: "nag-tibba",
    name: "Nag Tibba Weekend Summit",
    location: "Uttarakhand",
    region: "India",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=85",
    ],
    tagline: "A first Himalayan summit, just a night bus away.",
    description: "The perfect reset for a long weekend. Walk through cedar forests, sleep under an ocean of stars, and catch the sunrise over five Himalayan ranges.",
    duration: "2D / 1N",
    difficulty: "Easy",
    altitude: "9,915 Ft",
    distance: "16 km",
    baseCamp: "Pantwari",
    rating: 4.8,
    reviewCount: 327,
    price: 2899,
    originalPrice: 3899,
    badge: "Friday night bus",
    categories: ["Weekend", "Beginner", "Himalayas"],
    batches: [
      { id: 301, startDate: "Jun 06", endDate: "Jun 07, 2026", slotsLeft: 8, price: 2899 },
      { id: 302, startDate: "Jun 13", endDate: "Jun 14, 2026", slotsLeft: 16, price: 2899 },
    ],
    itinerary: [
      { day: 1, title: "Dehradun to Pantwari & Camp", description: "Scenic drive to the trailhead, followed by a forest climb into camp.", distance: "5 km", altitude: "8,500 Ft", meal: "Lunch, dinner" },
      { day: 2, title: "Summit sunrise & Return", description: "Climb to the summit for sunrise, then descend for a late breakfast.", distance: "11 km", altitude: "9,915 Ft", meal: "Breakfast, lunch" },
    ],
  },
  {
    id: 4,
    slug: "valley-of-flowers",
    name: "Valley of Flowers & Hemkund",
    location: "Uttarakhand",
    region: "India",
    image: "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1600&q=85",
    ],
    tagline: "A living carpet of alpine blooms beneath Nanda Devi.",
    description: "Every monsoon, the Valley of Flowers turns into a surreal high-altitude garden. Pair it with Hemkund Sahib for a week of rare mountain stillness.",
    duration: "6D / 5N",
    difficulty: "Moderate",
    altitude: "14,107 Ft",
    distance: "38 km",
    baseCamp: "Govindghat",
    rating: 4.9,
    reviewCount: 216,
    price: 9999,
    originalPrice: 12499,
    badge: "Monsoon special",
    categories: ["Monsoon", "Wildflowers", "Himalayas"],
    batches: [
      { id: 401, startDate: "Jul 04", endDate: "Jul 09, 2026", slotsLeft: 10, price: 9999 },
      { id: 402, startDate: "Jul 18", endDate: "Jul 23, 2026", slotsLeft: 7, price: 9999 },
    ],
    itinerary: [
      { day: 1, title: "Arrival in Govindghat", description: "Settle into the valley, meet the team, and prepare.", distance: "—", altitude: "6,200 Ft", meal: "Dinner" },
      { day: 2, title: "Govindghat to Ghangaria", description: "Follow the Pushpawati river through a cool forest to base camp.", distance: "14 km", altitude: "10,000 Ft", meal: "Breakfast, lunch, dinner" },
      { day: 3, title: "Explore the Valley of Flowers", description: "Full day among rare blooms and waterfalls.", distance: "8 km", altitude: "12,700 Ft", meal: "Breakfast, lunch, dinner" },
    ],
  },
  {
    id: 5,
    slug: "triund",
    name: "Triund Ridge & Snowline",
    location: "Himachal Pradesh",
    region: "India",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=85",
    ],
    tagline: "Big views, little effort, zero reason to stay in.",
    description: "Triund's easy trail is a gateway to the Dhauladhar: a quick climb through pine forests to one of the most rewarding camps in the north.",
    duration: "2D / 1N",
    difficulty: "Easy",
    altitude: "9,350 Ft",
    distance: "14 km",
    baseCamp: "McLeod Ganj",
    rating: 4.7,
    reviewCount: 403,
    price: 1999,
    originalPrice: 2990,
    badge: "Easy escape",
    categories: ["Weekend", "Beginner", "Camping"],
    batches: [
      { id: 501, startDate: "Jun 06", endDate: "Jun 07, 2026", slotsLeft: 18, price: 1999 },
      { id: 502, startDate: "Jun 27", endDate: "Jun 28, 2026", slotsLeft: 11, price: 1999 },
    ],
    itinerary: [
      { day: 1, title: "McLeod Ganj to Triund", description: "Climb through oak and rhododendron forests to camp above clouds.", distance: "7 km", altitude: "9,350 Ft", meal: "Lunch, dinner" },
      { day: 2, title: "Sunrise & Descend", description: "Coffee with a view, then easy descent back into town.", distance: "7 km", altitude: "5,800 Ft", meal: "Breakfast" },
    ],
  },
  {
    id: 6,
    slug: "kashmir-great-lakes",
    name: "Kashmir Great Lakes",
    location: "Kashmir",
    region: "India",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1400&q=85",
    gallery: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1400&q=85"],
    tagline: "Turquoise glacial waters across seven dramatic alpine valleys.",
    description: "Kashmir Great Lakes is renowned worldwide for its 7 emerald alpine tarns nestled under high snow-clad peaks.",
    duration: "7D / 6N",
    difficulty: "Challenging",
    altitude: "13,800 Ft",
    distance: "72 km",
    baseCamp: "Shitkadi / Sonamarg",
    rating: 5.0,
    reviewCount: 310,
    price: 15999,
    originalPrice: 18999,
    badge: "Pristine",
    categories: ["High Pass", "Himalayas", "Lakes"],
    batches: [
      { id: 601, startDate: "Jul 11", endDate: "Jul 17, 2026", slotsLeft: 5, price: 15999 },
      { id: 602, startDate: "Jul 25", endDate: "Jul 31, 2026", slotsLeft: 9, price: 15999 },
    ],
    itinerary: [
      { day: 1, title: "Arrival in Sonamarg", description: "Meet your crew and acclimate.", distance: "—", altitude: "7,800 Ft", meal: "Dinner" },
      { day: 2, title: "Sonamarg to Nichnai", description: "Trek through silver birch woods to the Nichnai valley.", distance: "11 km", altitude: "11,500 Ft", meal: "Breakfast, lunch, dinner" },
    ],
  },
];

export const trailReports = [
  {
    id: 1,
    trail: "Kedarkantha",
    region: "Uttarakhand (Sankri)",
    status: "open",
    temperature: "2°C Night",
    weather: "Clear Skies",
    updatedAt: "10 min ago",
    note: "Clear skies and stable summit conditions.",
  },
  {
    id: 2,
    trail: "Hampta Pass",
    region: "Himachal Pradesh (Jobra)",
    status: "active",
    temperature: "8°C",
    weather: "Monsoon Green",
    updatedAt: "25 min ago",
    note: "River crossing is clear and well-guided.",
  },
  {
    id: 3,
    trail: "Pin Bhaba Pass",
    region: "Himachal Pradesh",
    status: "caution",
    temperature: "1°C",
    weather: "High Altitude Winds",
    updatedAt: "40 min ago",
    note: "High altitude clearance checked by trek leaders.",
  },
  {
    id: 4,
    trail: "Valley of Flowers",
    region: "Uttarakhand",
    status: "open",
    temperature: "14°C",
    weather: "Floral Blooms",
    updatedAt: "1 hr ago",
    note: "Carpeted meadows in full seasonal bloom.",
  },
  {
    id: 5,
    trail: "Triund Ridge",
    region: "Himachal Pradesh",
    status: "open",
    temperature: "17°C",
    weather: "Sunny",
    updatedAt: "1 hr ago",
    note: "Panoramic sunset views across Dhauladhar range.",
  },
];
